export default {
    FETCH_JOKES_REQUEST : "FETCH_JOKES_REQUEST",
    FETCH_JOKES_SUCCESS : "FETCH_JOKES_SUCCESS",

    FETCH_JOD_REQUEST : "FETCH_JOD_REQUEST",
    FETCH_JOD_SUCCESS : "FETCH_JOD_SUCCESS"
}